raw_datasets: ['GSM8K']
data_formats:
  CSQA: jsonl
  GSM8K: jsonl
test_config:
  model: gpt-3.5-turbo
  batch_size: 16
  temperature: 1.0
  max_tokens: 512
  frequency_penalty: 0
  presence_penalty: 0
  n: 1
start_point: 0
end_point: 9