raw_datasets: ['GSM8K']
data_formats:
  CSQA: jsonl
  GSM8K: jsonl
examiner_config:
  model: gpt-3.5-turbo
  batch_size: 32
  temperature: 1.0
  max_tokens: 256
  frequency_penalty: 0
  presence_penalty: 0
  n: 16
examinee_config:
  model: gpt-3.5-turbo
  batch_size: 32
  temperature: 1.0
  max_tokens: 512
  frequency_penalty: 0
  presence_penalty: 0
  n: 20
start_point: 0
end_point: 49
step_num: 3
beam_width: 4